# Generated by Django 2.0.3 on 2018-09-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cemex', '0003_auto_20180725_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=30)),
                ('address2', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='order_address',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemex.Order'),
        ),
    ]
