# Generated by Django 2.0.3 on 2018-09-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cemex', '0004_auto_20180914_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_address',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
